platform :ios, '8.0'
#use_frameworks!个别需要用到它，比如reactiveCocoa

target ‘hhhy’ do
  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage', '~> 4.0.0-beta2'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'ZXingObjC','~> 3.1.0'

end